import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`position-relative ${styles.hero}`}>
          <div className={styles.heroHeadingContainer}>
            <div className={`px-4 text-white ${styles.heroHeadingContent}`}>
              <h1>Adopt Globally, Adopt Locally</h1>
              <p className="mb-4">
                Daya Dimensi Indonesia is a world-class strategic partner for
                individual and organisational transformation through
                humanity-based and technology-supported solutions to help you
                hire, promote, and develop exceptional leaders.
              </p>
              <div className={`d-flex ${styles.heroMore}`}>
                <Link href={"/"} className="d-flex align-items-center">
                  <p className="mb-0 me-2 text-white">Learn more about us</p>
                  <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
                </Link>
                <Link href={"/"} className="d-flex align-items-center">
                  <p className="mb-0 me-2 text-white">Contact us</p>
                  <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
                </Link>
              </div>
            </div>
          </div>
          <div
            className={`d-flex position-absolute align-items-center bottom-0 ${styles.heroSectionBottom}`}
          >
            <div
              className={`bg-white d-flex align-items-center ${styles.heroDiscoverContainer}`}
            >
              <div className={`me-4 d-flex ${styles.heroDiscoverBtn}`}>
                <p className="fs-12px">DISCOVER</p>
                <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
              </div>
              <div className={`d-flex ${styles.heroDiscoverContent}`}>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    24+ Years
                  </p>
                  <p>Experience</p>
                </div>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    50.000+
                  </p>
                  <p>Executive Clients</p>
                </div>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    400+
                  </p>
                  <p>Organization Clients</p>
                </div>
              </div>
            </div>
            <div className={`d-flex ${styles.heroSectionBottomCertification}`}>
              <Image
                src={"/principles.png"}
                alt="principles"
                width={195}
                height={64}
              />
              <Image
                src={"/certification.png"}
                alt="certification"
                width={280}
                height={64}
              />
            </div>
          </div>
          <div className={`position-absolute${styles.heroOverlay}`}></div>
        </div>
      </main>
    </>
  );
}
