import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const expertises = [
  {
    icon: "learning.svg",
    text: "Applied Science & Imagination Centre",
    img: "",
  },
  {
    icon: "diagnostic.svg",
    text: "Diagnostics and Assessments",
    img: "",
  },
  {
    icon: "transformation.svg",
    text: "Human Resources & Organizational Transformation",
    img: "",
  },
  {
    icon: "klobility.svg",
    text: "Klobility",
    img: "",
  },
  {
    icon: "executive.svg",
    text: "Leadership Development",
    img: "",
  },
  {
    icon: "learning.svg",
    text: "On-Demand Online Learning",
    img: "",
  },
];

const events = [
  {
    type: "PUBLIC WORKSHOP",
    date: "25 Feb 2022",
    title: "Zoompathy vs Zoom-fatigue: Managing Virtual Meeting Burnout",
  },
  {
    type: "BUKA PINTU",
    date: "25 Feb 2022",
    title: "Our New Solution To Hire The Right Person For Your Company",
  },
  {
    type: "LIVE WEBINAR",
    date: "25 Feb 2022",
    title: "DDI : Among Indonesia’s First Signatories of UN WEP",
  },
  {
    type: "BUKA PINTU",
    date: "25 Feb 2022",
    title: "Our New Solution To Hire The Right Person For Your Company",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`position-relative ${styles.hero}`}>
          <div className={styles.heroHeadingContainer}>
            <div className={`px-4 text-white ${styles.heroHeadingContent}`}>
              <h1>Adopt Globally, Adopt Locally</h1>
              <p className="mb-4">
                Daya Dimensi Indonesia is a world-class strategic partner for
                individual and organisational transformation through
                humanity-based and technology-supported solutions to help you
                hire, promote, and develop exceptional leaders.
              </p>
              <div className={`d-flex ${styles.heroMore}`}>
                <Link href={"/"} className="d-flex align-items-center">
                  <p className="mb-0 me-2 text-white">Learn more about us</p>
                  <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
                </Link>
                <Link href={"/"} className="d-flex align-items-center">
                  <p className="mb-0 me-2 text-white">Contact us</p>
                  <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
                </Link>
              </div>
            </div>
          </div>
          <div
            className={`d-flex position-absolute align-items-center bottom-0 ${styles.heroSectionBottom}`}
          >
            <div
              className={`bg-white d-flex align-items-center ${styles.heroDiscoverContainer}`}
            >
              <div className={`me-4 d-flex ${styles.heroDiscoverBtn}`}>
                <p className="fs-12px">DISCOVER</p>
                <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
              </div>
              <div className={`d-flex ${styles.heroDiscoverContent}`}>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    24+ Years
                  </p>
                  <p>Experience</p>
                </div>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    50.000+
                  </p>
                  <p>Executive Clients</p>
                </div>
                <div>
                  <p className={`fs-2 mb-0 ${styles.heroDiscoverHeading}`}>
                    400+
                  </p>
                  <p>Organization Clients</p>
                </div>
              </div>
            </div>
            <div className={`d-flex ${styles.heroSectionBottomCertification}`}>
              <Image
                src={"/principles.png"}
                alt="principles"
                width={195}
                height={64}
              />
              <Image
                src={"/certification.png"}
                alt="certification"
                width={280}
                height={64}
              />
            </div>
          </div>
          <div className={`position-absolute${styles.heroOverlay}`}></div>
        </div>
        <div className={`${styles.sectionExpertise}`}>
          <h2>Expertise</h2>
          <p>
            "Organisations who will succeed in the long-run are those who are
            open to new ideas, embrace innovations, instill compassion in every
            act and decision, and consistent in advancing humanity through
            sustainability." - Excerpts from 'Leaders of a New Planet' book.
          </p>
          <div className={styles.expertiseGrid}>
            {expertises.length &&
              expertises.map((expertise, i) => (
                <div
                  className={`p-4 position-relative ${styles.expertiseBox}`}
                  key={i}
                >
                  <Image
                    src={expertise.icon}
                    alt="icon"
                    width={49}
                    height={49}
                    className="mb-3"
                  />
                  <p className="text-uppercase text-white fs-3">
                    {expertise.text}
                  </p>
                  <Image
                    src={"arrow.svg"}
                    alt="arrow"
                    width={40}
                    height={40}
                    className={styles.expertiseArrow}
                  />
                </div>
              ))}
          </div>
        </div>
        <div className={styles.sectionEvents}>
          <div className="d-flex justify-content-between align-items-center mb-4">
            <h2>Upcoming Events</h2>
            <div className="d-flex">
              <p>View all</p>
              <Image src={"arrow.svg"} alt="arrow" width={20} height={20} />
            </div>
          </div>
          <div className={`d-flex ${styles.eventsContentContainer}`}>
            <Image
              src={"/img-upcoming.png"}
              alt="events"
              width={481}
              height={481}
            />
            <div>
              {events.length &&
                events.map((event, i) => (
                  <div className={`d-flex ${styles.eventContent}`} key={i}>
                    <div>
                      <p className={styles.eventType}>{event.type}</p>
                      <p className={styles.eventDate}>{event.date}</p>
                    </div>
                    <div>
                      <p className="fs-4">{event.title}</p>
                    </div>
                    <Image
                      src={"arrow.svg"}
                      alt="arrow"
                      width={25}
                      height={24}
                    />
                  </div>
                ))}
            </div>
          </div>
        </div>
        <div
          className={`text-white d-flex align-items-center position-relative ${styles.sectionLearnmore}`}
        >
          <div className={`position-relative z-1 ${styles.sectionContent}`}>
            <h2>Be a Part of Daya Dimensi Indonesia</h2>
            <p>
              Are you the resilient leaders we are searching for? Join Daya
              Dimensi Indonesia to advance your leadership skill and generate
              exceptional leaders across Indonesia at once.
            </p>
            <Link href={"/"} className="text-white">
              <div className="d-flex align-items-center">
                <p className="mb-0 me-">Learn more</p>
                <Image src={"arrow.svg"} alt="arrow" width={24} height={24} />
              </div>
            </Link>
          </div>
          <div className={styles.learnmoreOverlay}></div>
        </div>
      </main>
    </>
  );
}
